### PR TITLE
auto update

### PR DESCRIPTION
**Pull request by yorkie**
this adds auto-update feature, you should be able to use this feature by configuring 3rd argument of Parser constructor:
```js
var psr = new Parser('pattern.dat', [..], {autoUpdate: true, key: '...'});
// now this parser `psr` will get data automatically from 51Degrees
```

R= @nerru86

### CODE REVIEW

**Comment by review-ninja** [comment]
[ReviewNinja](http://app.review.ninja/51Degreesmobi/51degrees.node/pull/21)

**Comment by yorkie** [comment]
fixed typo, thanks @Osterjour

**Comment by yorkie** [comment]
Also added `last-modified` set, but as for `md5` check, i still have the best solution to check, because our data file is about 20MB, if we calaluate the value in-memory, it would cause some other problems, solution maybe:

1. `child_process` so that operation would not effect the current worker process
2. `stream`, this module can reduce the consume

@nerru86 @Osterjour any thoughts?

**Comment by yorkie** [comment]
@nerru86 could you help me review again? i have updated and added the "md5 checksum" feature in this patch :)

**Comment by yorkie** [comment]
Fixed bugs via c4f6115

**Comment by yorkie** [comment]
> If they don’t want to use the auto update.

```js
var psr1 = new Parser('51Degrees-Lite', properties, {
  autoUpdate: false,
  key: 'license key'
});
```

> If they want to use automatic data update.

```js
var psr1 = new Parser('51Degrees-Lite', properties, {
  autoUpdate: true,
  key: 'license key'
});
```

> If they want to call the auto-update manually.

```js
var psr1 = new Parser('51Degrees-Lite', properties);
psr3.update('51Degrees-Lite.dat', props, 'license key', function onupdated () {
  // todo: updated
});
```

/cc @nerru86

**Comment by yorkie** [comment]
Merged absolutely, Thanks for your reviewing work @nerru86

**Pull request merged**
